import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { Box } from "@mui/material";
import { LeftContainer } from "./page";
import ReduxProdiver from "@/Providers/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NewsWave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  right
}: Readonly<{
  children: React.ReactNode;
  right: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/logo.png"
          type="image/png"
        />
      </head>
      <body className={inter.className}>
        <ReduxProdiver>

          <Navbar />
          <Box
            sx={{
              // bgcolor: 'red',
              padding: { md: 5, xs: 0 },
              px: { md: 2, xs: 1 },
              paddingTop: { xs: 9, md: 5 },
              display: 'flex'
              , gap: 1,
              justifyContent: 'center',
              maxHeight: '91vh',
              overflow: 'hidden'
              // alignItems: 'center'
            }}
          >
            <LeftContainer />
            {children}
            {right}
          </Box>
        </ReduxProdiver>
      </body>
    </html>
  );
}
